In [4]:
import pandas as pd
import numpy as np
from sklearn.neighbors import LSHForest
import math
import operator
from sklearn.cross_validation import KFold
from sklearn.metrics import accuracy_score,f1_score
import warnings
warnings.filterwarnings("ignore")
X_data = pd.read_csv("../data/dolphins/dolphins.csv",encoding = 'utf8',sep='\s+',header=None)
y_data = pd.read_csv("../data/dolphins/dolphins_label.csv",encoding = 'utf8',sep='\s+',names=['label'])


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
def most_common(lst):
    return max(set(lst), key=lst.count)

In [20]:
X = np.array(X_data)
y = np.array(y_data)
kf = KFold(y.shape[0],n_folds=10)
lshf = LSHForest(random_state=42)
n_neighbors=5



for train_index, validation_index in kf:
            
    X_train, X_val = X[train_index], X[validation_index]
    y_train, y_val = y[train_index], y[validation_index]
    #print(y_train[0])
    lshf.fit(X_train)
    distances, indices = lshf.kneighbors(X_val, n_neighbors=5)
    index = indices.tolist()
    predicted = []
    predicted_label=[]
    for i in index:
        row=[]
        for j in i:
            
            y_pred = y_train[j]
            row.append(y_pred)
        
        predicted.append(row)
    #print(np.asarray(predicted))
    final=np.resize(np.asarray(predicted),(X_val.shape[0],n_neighbors))
    for lst in final.tolist():
        y_val_pred = most_common(lst)
        predicted_label.append(y_val_pred)
    print(y_val) 
    y_test=np.resize(y_val,(1,X_val.shape[0])).tolist()[0]
    #print(y_test.tolist()[0])
    print("-----------")
    print(predicted_label)
    accuracy = accuracy_score(y_test, predicted_label)
    f1scoremacro = f1_score(y_test, predicted_label,average='macro')
    f1scoremicro = f1_score(y_test, predicted_label,average='micro')
            
        

/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


[[0]
 [0]
 [0]
 [0]
 [0]
 [2]
 [0]]
-----------
[0, 0, 0, 0, 0, 2, 0]
[[1]
 [3]
 [1]
 [1]
 [1]
 [1]
 [1]]
-----------
[1, 0, 1, 1, 1, 1, 1]
[[1]
 [0]
 [0]
 [0]
 [0]
 [2]]
-----------
[1, 1, 0, 0, 0, 0]
[[2]
 [2]
 [2]
 [2]
 [1]
 [1]]
-----------
[2, 2, 2, 2, 1, 1]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
-----------
[1, 1, 1, 1, 1, 0]
[[0]
 [2]
 [0]
 [1]
 [2]
 [2]]
-----------
[0, 2, 0, 1, 2, 2]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]]
-----------
[0, 0, 0, 0, 0, 0]
[[0]
 [0]
 [2]
 [2]
 [2]
 [1]]
-----------
[0, 0, 2, 2, 2, 1]
[[1]
 [1]
 [2]
 [2]
 [2]
 [1]]
-----------
[1, 1, 2, 2, 2, 1]
[[0]
 [3]
 [0]
 [0]
 [0]
 [1]]
-----------
[0, 1, 0, 0, 0, 1]


In [31]:
pubmed=pd.read_csv("../data/pubmed/pubmed.csv",encoding = 'utf8',sep='\s+',header=None)
from sklearn.metrics import f1_score
def evaluation_pubmedLSH():
    Accuracy=dict()
    F1scoremacro=dict()
    F1scoremicro=dict()
    for file in [2,4,8,16,32]:
        filename =  '../Reduced_dim/pubmed/pubmed_%d.csv'%(file,)
        print(filename)
        X=pd.read_csv(filename,encoding = 'utf8',header=None)
        y=pd.read_csv("../data/pubmed/pubmed_label.csv",encoding = 'utf8',names = ["label"])
        
        X = np.array(X)
        y = np.array(y)
    
        kf = KFold(y.shape[0],n_folds=10)
        lshf = LSHForest(random_state=42)
        n_neighbors=5
        
        
        accuracies=[]
        f1scoremacro=[]
        f1scoremicro=[]
        for train_index, validation_index in kf:
           #print("TRAIN:", train_index, "TEST:", test_index)
            
            #print(X)
            
            X_train, X_val = X[train_index], X[validation_index]
            y_train, y_val = y[train_index], y[validation_index]
            lshf.fit(X_train)
            distances, indices = lshf.kneighbors(X_val, n_neighbors=5)
            index = indices.tolist()
            predicted = []
            predicted_label=[]
            for i in index:
                row=[]
                for j in i:

                    y_pred = y_train[j]
                    row.append(y_pred)

                predicted.append(row)
            #print(np.asarray(predicted))
            final=np.resize(np.asarray(predicted),(X_val.shape[0],n_neighbors))
            for lst in final.tolist():
                y_val_pred = most_common(lst)
                predicted_label.append(y_val_pred)
            #print(y_val) 
            y_test=np.resize(y_val,(1,X_val.shape[0])).tolist()[0]
            #print(y_test.tolist()[0])
            #print("-----------")
            #print(predicted_label)
            accuracy = accuracy_score(y_test, predicted_label)
            f1_scoremacro = f1_score(y_test, predicted_label,average='macro')
            f1_scoremicro = f1_score(y_test, predicted_label,average='micro')
            accuracies.append(accuracy)
            f1scoremacro.append(f1_scoremacro)
            f1scoremicro.append(f1_scoremicro)
        #print(accuracies)
        #print(sum(accuracies)/float(len(accuracies)))
        Accuracy[file]=sum(accuracies)/float(len(accuracies))
        F1scoremacro[file]=sum(f1scoremacro)/float(len(f1scoremacro))
        F1scoremicro[file]=sum(f1scoremicro)/float(len(f1scoremicro))
    return Accuracy,F1scoremacro,F1scoremicro


In [32]:
Accuracy,F1scoremacro,F1scoremicro = evaluation_pubmedLSH()

../Reduced_dim/pubmed/pubmed_2.csv


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/random_projection.py:378: DataDimensionalityWarning: The number of components is higher than the number of features: n_features < n_components (2 < 32).The dimensionality of the problem will not be reduced.
  DataDimensionalityWarning)


../Reduced_dim/pubmed/pubmed_4.csv


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/random_projection.py:378: DataDimensionalityWarning: The number of components is higher than the number of features: n_features < n_components (4 < 32).The dimensionality of the problem will not be reduced.
  DataDimensionalityWarning)


../Reduced_dim/pubmed/pubmed_8.csv


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/random_projection.py:378: DataDimensionalityWarning: The number of components is higher than the number of features: n_features < n_components (8 < 32).The dimensionality of the problem will not be reduced.
  DataDimensionalityWarning)


../Reduced_dim/pubmed/pubmed_16.csv


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/random_projection.py:378: DataDimensionalityWarning: The number of components is higher than the number of features: n_features < n_components (16 < 32).The dimensionality of the problem will not be reduced.
  DataDimensionalityWarning)


../Reduced_dim/pubmed/pubmed_32.csv


/home/nidhi/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)


In [33]:
print(Accuracy)

{2: 0.3544743956687358, 4: 0.3520604296274525, 8: 0.3598380441197396, 16: 0.3644754920141732, 32: 0.363461139219542}


In [34]:
import pickle


f = open("evaluation_pubmedLSH", "wb")
pickle.dump(Accuracy,f)
pickle.dump(F1scoremacro, f)
pickle.dump(F1scoremicro,f)
f.close()

In [35]:
f = open("evaluation_pubmedLSH", "rb")
value1 = pickle.load(f)
value2 = pickle.load(f)
value3 = pickle.load(f)
f.close()


In [37]:
print(value1)
print(value2)
print(value3)

{2: 0.3544743956687358, 4: 0.3520604296274525, 8: 0.3598380441197396, 16: 0.3644754920141732, 32: 0.363461139219542}
{2: 0.33043870612100046, 4: 0.3316484202782873, 8: 0.33899516150998166, 16: 0.3446773648411173, 32: 0.3425210504477797}
{2: 0.3544743956687358, 4: 0.3520604296274525, 8: 0.3598380441197396, 16: 0.3644754920141732, 32: 0.363461139219542}


In [10]:

from sklearn.metrics import f1_score
def evaluation_twitterLSH():
    Accuracy=dict()
    F1scoremacro=dict()
    F1scoremicro=dict()
    
    
    file_y = "../data/twitter/twitter_label.txt"
    with open(file_y) as f:
        content_y = f.readlines()
    y = [str(x.strip()) for x in content_y]
    y = np.array(y)
    
       
    
    for file in [2,4,8,16,32,64,128,256,512,1024]:
        filename =  '../Reduced_dim/twitter/twitter_%d.csv'%(file,)
        print(filename)
        X=pd.read_csv(filename,encoding = 'utf8',header=None)
        
    
        X = np.array(X)
        
    
        kf = KFold(y.shape[0],n_folds=10)
        lshf = LSHForest(random_state=42)
        n_neighbors=5
        
        
        accuracies=[]
        f1scoremacro=[]
        f1scoremicro=[]
        for train_index, validation_index in kf:
           #print("TRAIN:", train_index, "TEST:", test_index)
            
            #print(X)
            
            X_train, X_val = X[train_index], X[validation_index]
            y_train, y_val = y[train_index], y[validation_index]
            lshf.fit(X_train)
            distances, indices = lshf.kneighbors(X_val, n_neighbors=5)
            index = indices.tolist()
            predicted = []
            predicted_label=[]
            for i in index:
                row=[]
                for j in i:

                    y_pred = y_train[j]
                    row.append(y_pred)

                predicted.append(row)
            #print(np.asarray(predicted))
            final=np.resize(np.asarray(predicted),(X_val.shape[0],n_neighbors))
            for lst in final.tolist():
                y_val_pred = most_common(lst)
                predicted_label.append(y_val_pred)
            #print(y_val) 
            y_test=np.resize(y_val,(1,X_val.shape[0])).tolist()[0]
            #print(y_test.tolist()[0])
            #print("-----------")
            #print(predicted_label)
            accuracy = accuracy_score(y_test, predicted_label)
            f1_scoremacro = f1_score(y_test, predicted_label,average='macro')
            f1_scoremicro = f1_score(y_test, predicted_label,average='micro')
            accuracies.append(accuracy)
            f1scoremacro.append(f1_scoremacro)
            f1scoremicro.append(f1_scoremicro)
        #print(accuracies)
        #print(sum(accuracies)/float(len(accuracies)))
        Accuracy[file]=sum(accuracies)/float(len(accuracies))
        F1scoremacro[file]=sum(f1scoremacro)/float(len(f1scoremacro))
        F1scoremicro[file]=sum(f1scoremicro)/float(len(f1scoremicro))
    return Accuracy,F1scoremacro,F1scoremicro


In [11]:
Accuracy,F1scoremacro,F1scoremicro = evaluation_twitterLSH()

../Reduced_dim/twitter/twitter_2.csv
../Reduced_dim/twitter/twitter_4.csv
../Reduced_dim/twitter/twitter_8.csv
../Reduced_dim/twitter/twitter_16.csv
../Reduced_dim/twitter/twitter_32.csv
../Reduced_dim/twitter/twitter_64.csv
../Reduced_dim/twitter/twitter_128.csv
../Reduced_dim/twitter/twitter_256.csv
../Reduced_dim/twitter/twitter_512.csv
../Reduced_dim/twitter/twitter_1024.csv


In [13]:
import pickle


f = open("evaluation_twitterLSH", "wb")
pickle.dump(Accuracy,f)
pickle.dump(F1scoremacro, f)
pickle.dump(F1scoremicro,f)
f.close()

In [12]:
print(Accuracy)

{2: 0.4078333333333333, 4: 0.41100000000000003, 8: 0.41166666666666674, 16: 0.4141666666666667, 32: 0.44400000000000006, 64: 0.44300000000000006, 128: 0.45583333333333337, 256: 0.479, 512: 0.47833333333333333, 1024: 0.49849999999999994}


In [14]:
pubmed=pd.read_csv("../data/dolphins/dolphins.csv",encoding = 'utf8',sep='\s+',header=None)
from sklearn.metrics import f1_score
def evaluation_dolphinsLSH():
    Accuracy=dict()
    F1scoremacro=dict()
    F1scoremicro=dict()
    for file in [2,4,8,16]:
        filename =  '../Reduced_dim/dolphins/dolphins_%d.csv'%(file,)
        print(filename)
        X=pd.read_csv(filename,encoding = 'utf8',header=None)
        y=pd.read_csv("../data/dolphins/dolphins_label.csv",encoding = 'utf8',names = ["label"])
        
        X = np.array(X)
        y = np.array(y)
    
        kf = KFold(y.shape[0],n_folds=10)
        lshf = LSHForest(random_state=42)
        n_neighbors=5
        
        
        accuracies=[]
        f1scoremacro=[]
        f1scoremicro=[]
        for train_index, validation_index in kf:
           #print("TRAIN:", train_index, "TEST:", test_index)
            
            #print(X)
            
            X_train, X_val = X[train_index], X[validation_index]
            y_train, y_val = y[train_index], y[validation_index]
            lshf.fit(X_train)
            distances, indices = lshf.kneighbors(X_val, n_neighbors=5)
            index = indices.tolist()
            predicted = []
            predicted_label=[]
            for i in index:
                row=[]
                for j in i:

                    y_pred = y_train[j]
                    row.append(y_pred)

                predicted.append(row)
            #print(np.asarray(predicted))
            final=np.resize(np.asarray(predicted),(X_val.shape[0],n_neighbors))
            for lst in final.tolist():
                y_val_pred = most_common(lst)
                predicted_label.append(y_val_pred)
            #print(y_val) 
            y_test=np.resize(y_val,(1,X_val.shape[0])).tolist()[0]
            #print(y_test.tolist()[0])
            #print("-----------")
            #print(predicted_label)
            accuracy = accuracy_score(y_test, predicted_label)
            f1_scoremacro = f1_score(y_test, predicted_label,average='macro')
            f1_scoremicro = f1_score(y_test, predicted_label,average='micro')
            accuracies.append(accuracy)
            f1scoremacro.append(f1_scoremacro)
            f1scoremicro.append(f1_scoremicro)
        #print(accuracies)
        #print(sum(accuracies)/float(len(accuracies)))
        Accuracy[file]=sum(accuracies)/float(len(accuracies))
        F1scoremacro[file]=sum(f1scoremacro)/float(len(f1scoremacro))
        F1scoremicro[file]=sum(f1scoremicro)/float(len(f1scoremicro))
    return Accuracy,F1scoremacro,F1scoremicro


In [15]:
Accuracy,F1scoremacro,F1scoremicro = evaluation_dolphinsLSH()

../Reduced_dim/dolphins/dolphins_2.csv
../Reduced_dim/dolphins/dolphins_4.csv
../Reduced_dim/dolphins/dolphins_8.csv
../Reduced_dim/dolphins/dolphins_16.csv


In [17]:
import pickle


f = open("evaluation_dolphinsLSH", "wb")
pickle.dump(Accuracy,f)
pickle.dump(F1scoremacro, f)
pickle.dump(F1scoremicro,f)
f.close()

In [16]:
print(Accuracy)

{2: 0.8023809523809524, 4: 0.8595238095238095, 8: 0.9047619047619049, 16: 0.9023809523809524}


In [ ]:

from sklearn.metrics import f1_score
def evaluation_twitterLSHoriginal():
    Accuracy=dict()
    F1scoremacro=dict()
    F1scoremicro=dict()
    
    
    file_y = "../data/twitter/twitter_label.txt"
    with open(file_y) as f:
        content_y = f.readlines()
    y = [str(x.strip()) for x in content_y]
    y = np.array(y)
    
       
    
    for file in [2,4,8,16,32,64,128,256,512,1024]:
        filename =  '../Reduced_dim/twitter/twitter_%d.csv'%(file,)
        print(filename)
        X=pd.read_csv(filename,encoding = 'utf8',header=None)
        
    
        X = np.array(X)
        
    
        kf = KFold(y.shape[0],n_folds=10)
        lshf = LSHForest(random_state=42)
        n_neighbors=5
        
        
        accuracies=[]
        f1scoremacro=[]
        f1scoremicro=[]
        for train_index, validation_index in kf:
           #print("TRAIN:", train_index, "TEST:", test_index)
            
            #print(X)
            
            X_train, X_val = X[train_index], X[validation_index]
            y_train, y_val = y[train_index], y[validation_index]
            lshf.fit(X_train)
            distances, indices = lshf.kneighbors(X_val, n_neighbors=5)
            index = indices.tolist()
            predicted = []
            predicted_label=[]
            for i in index:
                row=[]
                for j in i:

                    y_pred = y_train[j]
                    row.append(y_pred)

                predicted.append(row)
            #print(np.asarray(predicted))
            final=np.resize(np.asarray(predicted),(X_val.shape[0],n_neighbors))
            for lst in final.tolist():
                y_val_pred = most_common(lst)
                predicted_label.append(y_val_pred)
            #print(y_val) 
            y_test=np.resize(y_val,(1,X_val.shape[0])).tolist()[0]
            #print(y_test.tolist()[0])
            #print("-----------")
            #print(predicted_label)
            accuracy = accuracy_score(y_test, predicted_label)
            f1_scoremacro = f1_score(y_test, predicted_label,average='macro')
            f1_scoremicro = f1_score(y_test, predicted_label,average='micro')
            accuracies.append(accuracy)
            f1scoremacro.append(f1_scoremacro)
            f1scoremicro.append(f1_scoremicro)
        #print(accuracies)
        #print(sum(accuracies)/float(len(accuracies)))
        Accuracy[file]=sum(accuracies)/float(len(accuracies))
        F1scoremacro[file]=sum(f1scoremacro)/float(len(f1scoremacro))
        F1scoremicro[file]=sum(f1scoremicro)/float(len(f1scoremicro))
    return Accuracy,F1scoremacro,F1scoremicro
