In [1]:
import numpy as np
import pandas as pd


In [2]:
transformation_matrix

matrix([[ 1.92490929,  0.33668793,  1.01243419, ..., -1.16557147,
         -2.50073896, -1.12252534],
        [ 1.70329823, -0.06802693,  1.97602605, ...,  0.12397241,
         -0.20471181,  1.98986656],
        [-0.40431634,  1.63384193, -1.22350129, ...,  0.46419446,
         -0.58937251,  0.06978045],
        ..., 
        [-1.43855673, -0.33806437, -0.41477522, ...,  0.17288094,
          0.04579556,  1.1217146 ],
        [ 0.12933549,  1.46036802, -2.82027166, ..., -0.75828616,
         -0.56758667, -1.16437587],
        [-2.6498664 ,  0.04244101, -1.4063163 , ...,  1.62145179,
          1.37947415,  0.61166235]])

In [3]:
X=pd.read_csv("../data/dolphins/dolphins.csv",encoding = 'utf8',sep='\s+',header=None)



In [47]:
X=np.asmatrix(X)
print(X.shape)

(62, 32)


In [50]:
int((X.shape[1]/2 + 1))

17

In [5]:
#r_projections=3
for r_projections in range(2,int(X.shape[1]/2 +1),2):
    print(r_projections)
    rn=np.random.standard_normal(size=(X.shape[1])*r_projections)
    rn=rn.reshape((X.shape[1]),r_projections)
    transformation_matrix=np.asmatrix(rn)
    data=np.asmatrix(X)
    X_data = data * transformation_matrix
    #print(X_data)
    filename =  '/Reduced_dim/dolphins2/dolphins_%d.csv'%(r_projections,)
    np.savetxt(filename, X_data, delimiter=",")

2


FileNotFoundError: [Errno 2] No such file or directory: '/Reduced_dim/dolphins2/dolphins_2.csv'

In [54]:
dolphins16=pd.read_csv("..\Reduced_dim\dolphins\dolphins_16.csv",encoding = 'utf8',header=None)
print(dolphins16)

          0         1         2         3         4         5         6   \
0   0.214605 -2.297699  0.564841  2.191976  1.180133 -2.761756 -1.538267   
1  -0.067704 -2.076907  0.612608  1.554809  0.884543 -2.591274 -1.240526   
2   0.583781 -2.737428  0.228744  3.088775  1.708076 -3.205853 -1.836267   
3   0.258997 -2.521157  0.410321  1.911887  1.480762 -2.775685 -0.916404   
4   0.730859 -2.388551  0.476070  3.283290  1.242251 -3.416239 -2.378085   
5   0.481148 -2.335844  0.444388  1.785839  1.209180 -2.792812 -0.440138   
6   0.471178 -2.504494  0.513913  2.829014  1.234049 -3.094604 -1.855580   
7  -0.113284 -1.604174  1.028247  1.927149 -0.257703 -3.118980 -2.919549   
8  -0.098549 -1.570288  0.709483  1.166326  0.230701 -2.393839 -1.602676   
9  -1.334372 -1.572883  1.630013  1.276614 -1.509035 -3.158678 -4.065788   
10 -0.835321 -1.606928  1.516104  1.981750 -1.245079 -3.662801 -4.213591   
11 -0.254425 -1.600349  1.249509  2.189483 -0.478019 -3.285448 -3.371206   
12 -0.802918

In [56]:
int(Y.shape[1]/2 +1)

65

In [55]:
#r_projections=3
def pubmed():
    for r_projections in range(2,int(Y.shape[1]/2 +1),2):
        print(r_projections)
        rn=np.random.standard_normal(size=(Y.shape[1])*r_projections)
        rn=rn.reshape((Y.shape[1]),r_projections)
        transformation_matrix=np.asmatrix(rn)
        data=np.asmatrix(Y)
        Y_data = data * transformation_matrix
        print(Y_data)
        filename =  '/Users/Vikas/Desktop/tipr-first-assignment-master/Reduced_dim/pubmed/pubmed_%d.csv'%(r_projections,)
        np.savetxt(filename, Y_data, delimiter=",")

In [57]:
pubmed()

2
[[ 2.44210284 -1.70426002]
 [-1.08948282 -0.55841483]
 [-2.33186421  1.68662804]
 ..., 
 [-0.15715724  2.73955423]
 [-0.08430472 -5.84150397]
 [ 0.07829966  1.71660219]]
4
[[ 2.12541652 -1.73272484  1.00560641 -2.94030874]
 [-1.00885507  6.40886913  0.86375531  0.74740601]
 [-6.45965401  2.16333971  1.72858759  2.74414896]
 ..., 
 [ 4.89862506  1.56529508  0.55430802 -6.62737986]
 [-1.83276278 -1.4086307  -1.48652171 -2.84903676]
 [-0.96084404 -1.68893284  3.2258394   3.57590418]]
6
[[ -3.82938164   7.85607838   2.55876309   1.27334536  -1.4078695
   -6.69950974]
 [ -2.51263795   2.99609288   0.11155384  -1.29703945   3.24978907
   -0.65264745]
 [ -4.26214803   4.02666985   3.22909045  10.27938068   2.90587968
   -1.19840097]
 ..., 
 [ -1.21516171   3.63225949   5.34853251   5.10915531  -3.73660694
   -6.11753601]
 [ -1.71642434   5.67261406   0.46261295   2.2770873   -2.02213746
   -5.13493636]
 [ -3.93125345   4.20233495  -0.69015824   1.94515984  -0.4434612
   -2.99190885]]
8
[[-0

36
[[ -1.25422014e+00  -3.12108330e+00  -8.03908142e+00 ...,   1.28385700e+00
   -1.34400850e+00  -3.98297528e-01]
 [ -1.61010384e+00   2.00330124e+00   3.37132485e+00 ...,   4.79114863e+00
    5.52543424e-01  -2.27413772e-01]
 [ -3.55476770e+00   1.90099213e+00  -2.31435101e+00 ...,   4.93275606e+00
   -4.65323205e+00  -2.66324075e+00]
 ..., 
 [ -3.62782863e+00   1.26531425e+00  -4.23294201e-01 ...,  -4.23118784e+00
   -4.89320970e+00  -5.21407392e-01]
 [ -6.14079753e+00   3.45560911e+00   2.77620037e+00 ...,  -5.45147178e+00
   -1.18741046e+00   2.48380231e+00]
 [ -3.35219624e+00   2.52079099e+00  -1.64464350e+00 ...,   1.01896924e+00
   -2.63736683e-03   2.79997985e+00]]
38
[[ -2.39573436   2.37466135   4.03660372 ...,   3.81276164   0.29006271
   -3.07684933]
 [  6.27636024   2.17804902  -3.18055337 ...,   1.77387611   0.95174776
   -2.15368159]
 [  4.63526978  -0.13560391   1.85954521 ...,   3.05774345   1.12138829
  -10.31038968]
 ..., 
 [  1.36616616   0.98921851   2.96594076 ..

In [4]:
file = '../data/twitter/twitter.txt'
with open(file) as f:
    content = f.readlines()
content = [str(x.strip()) for x in content] 

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer


# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(content)
# summarize
#print(vectorizer.vocabulary_)
#print(vectorizer.idf_)
# encode document
vector = vectorizer.transform(content)
# summarize encoded vector
#print(vector.shape)
twitter_text = vector.toarray()

In [8]:
#content
def twitter():
    for r_projections in [2,4,8,16,32,64,128,256,512,1024]:
        rn=np.random.standard_normal(size=(twitter_text.shape[1])*r_projections)
        rn=rn.reshape((twitter_text.shape[1]),r_projections)
        transformation_matrix=np.asmatrix(rn)
        data=np.asmatrix(twitter_text)
        twitter_text1 = data * transformation_matrix
        #print(twitter_text1)
        filename =  '../Reduced_dim/twitter/twitter_%d.csv'%(r_projections,)
        np.savetxt(filename, twitter_text1, delimiter=",")

In [9]:
twitter()

In [66]:
for i in range(twitter_text.shape[1]):
    print(twitter_text[1][i])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [ ]:
twitter()

[[ 0.97716246  0.98036858]
 [ 0.63093322  1.78896928]
 [ 1.5692146  -0.47627052]
 ..., 
 [ 0.48980594  0.96581579]
 [ 2.05840769 -0.07965976]
 [ 0.94770519 -0.46970509]]
[[-0.52384929 -0.15211898  1.00393659 -0.17923898]
 [-0.19565795 -1.33418794 -0.44298024  0.16116572]
 [-0.89965327 -0.3080704  -1.72284543  0.90668685]
 ..., 
 [ 0.47427879 -0.31837714 -1.28050262 -1.18466554]
 [-1.01009131 -1.01906227 -1.12137266  0.31699401]
 [ 0.54878259 -1.17277063  0.00322569  1.45191475]]
[[-0.01200394 -1.7644787   0.25532729 -1.07139129  0.20150836  2.6246595 ]
 [-0.91901067 -1.85435763 -0.10995651  1.95557668  0.51270808 -0.87003868]
 [-0.47696258 -0.23897359  1.07917944  0.05917355 -1.47086166 -0.22980143]
 ..., 
 [ 0.9131083  -0.81806714  0.83259779 -0.26902367  0.3776445   0.29155095]
 [ 1.02885133  0.17926569 -0.81886431 -0.4002985  -1.74622516  0.28256986]
 [ 0.6378763   0.44023981  0.48141546 -0.85147585  1.18806311 -0.0702723 ]]
[[ 0.19322918  1.59903868  0.23925555 ...,  0.3278006   0.

[[ 0.42686093  1.02160141  1.85469819 ..., -0.59844169  2.6257194
  -0.9146874 ]
 [-1.1081332   0.46583508 -0.58931605 ...,  0.19997489 -0.08455839
  -1.53407432]
 [ 0.55459483  0.8327933  -0.07490771 ..., -1.87228901 -0.02431425
  -0.38258715]
 ..., 
 [-1.9441654   0.25033588  0.26041867 ...,  1.01383731 -0.67593045
   0.95740607]
 [-0.62073681  0.85688392 -0.50231585 ...,  1.96210809  0.89713805
  -2.66375994]
 [-0.26735761  0.47778616  2.11365818 ...,  0.21340921  0.95039927
   0.23971208]]
[[-1.48732221 -0.17550875 -0.3227782  ...,  0.2529555  -1.59134872
   0.74079137]
 [-0.5823565   0.38602156 -0.50275242 ...,  1.48451805  1.46176646
  -1.7983128 ]
 [-1.31601814 -1.34265804 -0.76343483 ..., -2.65073621 -1.0135137
  -0.59922371]
 ..., 
 [-1.55747578 -1.22977289 -0.78821537 ...,  0.46912953  0.036472
   0.63336066]
 [-0.09357484 -0.5935841   0.43263812 ..., -0.01621195  0.47808837
  -0.81205327]
 [-1.06314798  0.85477604 -0.35477603 ...,  0.14176018 -1.40252523
   0.05631514]]
[[-0

[[-0.0601091  -0.24919673 -0.14904725 ...,  0.14701942 -1.19117925
   0.82817475]
 [-0.16729635  1.30178917  0.07130883 ..., -0.25422478 -0.4975058
  -0.03637811]
 [ 1.13261685 -0.690554    0.22008037 ..., -1.27716265  0.51377464
  -1.28472446]
 ..., 
 [-1.70159851  0.13161989 -0.97874868 ...,  0.81745853 -0.22915528
  -0.66056895]
 [ 0.878538    0.37559814 -1.13956629 ...,  1.03212249  0.94443891
  -1.41808778]
 [-0.38192817 -0.21515104  0.58177154 ...,  0.07919787  0.21014381
  -0.81937946]]
[[ 2.81257806  0.74859274  0.54437217 ..., -0.86836537  1.70150776
   0.81501846]
 [-1.5088563  -0.86752976  0.34152121 ...,  0.84823463 -0.09891829
  -0.67304034]
 [ 0.89509331  1.82735263 -0.83248178 ..., -0.19371233 -0.45856604
   0.42276946]
 ..., 
 [-1.14180414  0.20228767  1.18273816 ...,  0.63683942  1.11837691
   0.41226013]
 [-1.54664256  1.11582743  1.20028237 ...,  1.02751965  1.06182816
   0.30070488]
 [-0.56581632  0.24706621  0.25436255 ...,  1.04536085  1.62920823
   0.83283143]]
[

[[ 1.03746171  0.99949333 -0.27365868 ..., -0.4853392  -1.58745024
  -0.40292526]
 [-1.41494003  0.20645862 -0.49635428 ..., -0.16467093 -1.96250086
   0.19131366]
 [ 1.52836005  0.39798318  2.65720168 ..., -1.199595    1.85425465
  -0.56690559]
 ..., 
 [-0.56544152  1.1751127  -0.96401479 ..., -0.5520695   1.56743005
  -0.79315279]
 [ 0.37586424 -0.16246515 -1.11211526 ...,  0.23490505 -0.712575
   1.02246567]
 [-1.7005668  -0.37555359 -0.83687043 ..., -0.47380774 -0.99411524
  -0.40750715]]
[[ 0.2484565   0.22695352  1.19262909 ..., -1.24202544  0.00879668
  -1.59878482]
 [ 1.03621568  0.62989824  1.4409446  ..., -2.38828987  0.9749919
  -0.0344627 ]
 [ 0.32442723 -0.77657013 -0.22091496 ..., -0.24199554 -1.25120642
   0.73979543]
 ..., 
 [ 0.153761    0.41991493  0.0264634  ...,  1.2979182  -0.32806749
  -0.21512643]
 [ 2.49483383  2.31808127  0.06179899 ..., -0.18366396 -0.95356303
  -0.88612183]
 [-0.4698837   0.50341462  0.22457244 ..., -0.90034421 -2.19163991
  -1.29910519]]
[[ 

[[-1.51547606 -1.05941778 -0.45990309 ..., -0.39747298 -0.52389643
   1.12107279]
 [-1.37414321  1.01995153 -1.1900244  ..., -0.22490337 -0.50432582
  -1.0987133 ]
 [-1.90255267 -1.04466998  0.84990083 ..., -0.29216007 -0.96289834
  -0.19588314]
 ..., 
 [ 0.67713134 -0.43921103 -0.85804353 ...,  0.3577015  -1.77941413
  -0.07040953]
 [ 1.03772785 -2.03532017 -0.30377311 ...,  0.69061627 -1.39828145
   0.56963763]
 [-1.51709528 -2.32431988 -0.45747451 ..., -1.1046733  -2.05448654
   0.52069358]]
[[-1.2964064   1.85405067  0.27518226 ..., -0.44123107 -0.47542785
  -0.44554814]
 [ 0.23527549  0.7240921  -0.53837196 ...,  0.70032632 -0.30229013
   0.99769022]
 [-1.42725338 -0.35844769 -0.23169011 ...,  1.63039952  0.21527411
   0.95508966]
 ..., 
 [ 1.81149426 -0.00302031 -1.70379724 ..., -0.1320763  -0.31555738
   2.53111985]
 [ 0.23402427 -0.27197165 -2.13826898 ...,  0.6750361   1.17732129
  -0.84073344]
 [-0.23197343  0.9715793  -0.96370999 ...,  0.37677072  1.00333839
   0.69089354]]


[[-2.17032233 -1.71414596 -0.87181474 ...,  0.12720187 -0.84390393
  -0.95721455]
 [ 0.30202726 -0.74095186  0.10492211 ..., -0.04831447  0.34470353
   1.5671705 ]
 [-0.27267485 -0.5234847  -0.12258219 ...,  0.28130013 -0.62704058
  -0.02085644]
 ..., 
 [-0.23939555  0.33257322  0.76909705 ..., -1.71720967 -0.83973162
   0.04337529]
 [ 0.92523913 -0.1954508  -0.36676712 ..., -0.52434309 -1.27584739
  -1.58529805]
 [-0.83042586 -0.83111085 -1.06009949 ...,  0.693047   -0.18878115
   0.02210318]]
[[ 0.77637202  1.2432421   0.21912752 ...,  1.29834939  2.12411327
  -0.1624923 ]
 [-0.58201394 -2.6158681  -0.97997222 ...,  1.02817159 -0.38420849
  -0.99749386]
 [ 1.7705854  -0.00315808 -0.32794664 ..., -0.5158225   0.06761334
   0.28259822]
 ..., 
 [-2.24993067 -0.17600025  0.61497277 ...,  0.40929938 -1.68702615
  -1.39410129]
 [-0.82741096 -0.26969254 -0.03267509 ...,  0.75602962 -0.76747066
  -1.84050142]
 [-1.55278869  1.19557694  0.55529907 ..., -1.14459258 -1.514721
  -2.94532908]]
[[

[[ 0.64563683 -1.75563757  0.33906403 ..., -0.23952574 -0.36966474
  -0.96053206]
 [-0.48506062 -0.27504063  1.01145278 ..., -0.0505781  -0.51501067
   0.65430731]
 [-0.13945023 -1.67431724 -0.30173151 ...,  0.47158806 -1.08179111
   1.8900988 ]
 ..., 
 [ 0.816386    0.00709275 -0.32115263 ...,  0.17350837  0.25139028
  -0.34365199]
 [-0.12393771  0.66754678  0.05745909 ..., -0.06129069  1.02079665
  -0.34725882]
 [-0.52704746 -0.77553554 -0.07407717 ...,  0.79313804 -0.65064104
  -1.28105448]]
[[-0.35537007  0.28651661 -0.99923011 ..., -0.21613569  0.62547793
  -1.00804378]
 [ 1.08779786  0.13379717  0.48355556 ...,  1.30032642 -0.07789848
   1.61712506]
 [-0.9452117   1.26771666  0.28655667 ...,  1.46245475  0.68596545
  -1.25783753]
 ..., 
 [ 0.0995516   0.06455871 -2.084097   ..., -1.06786958  0.83733064
  -1.13918698]
 [-0.09734399  1.33316334  0.81004502 ...,  1.30218581  0.39337067
   2.06439623]
 [-0.126876    0.9372592   0.67847453 ..., -1.999299   -0.33197346
  -0.84537566]]


[[ 0.10671211 -1.57325231  2.17151062 ...,  1.55798589  1.26127366
   1.56762644]
 [ 0.77551731 -0.03818303 -0.18767562 ...,  0.36655285 -0.44113036
   1.11968816]
 [ 0.66378587  0.6903381   0.0472731  ...,  0.86473478 -0.78686249
  -1.87071252]
 ..., 
 [ 0.60946451 -2.1344943  -0.49591379 ...,  0.34060234  1.96423793
   0.48071717]
 [ 0.64427452  0.94502165  0.53716553 ...,  1.18131292  0.97210376
  -1.18835712]
 [ 0.15360488 -2.09896524  1.23451507 ..., -0.0931138   0.54264534
   0.77229429]]
[[ 0.52157344 -0.753774   -0.46602759 ...,  0.48312444 -0.36578445
  -0.00765736]
 [-0.55565189  0.89491639  0.01872468 ..., -1.44971396  1.32454416
  -0.61054947]
 [ 1.06967249  1.01460676  0.30732078 ...,  2.54731833  0.26600191
   1.91224934]
 ..., 
 [-0.08238951  0.75644293 -0.56437191 ...,  1.49687918  1.61211741
   0.6086563 ]
 [-0.93456259  1.32327433 -0.56850021 ..., -0.16270544 -1.20051503
   0.66545574]
 [ 0.06893627  1.54854047 -0.24967128 ...,  0.40679863  1.12282794
   0.31359472]]


[[ 0.4393769  -1.5866898  -0.77861221 ..., -0.78696794  0.50186302
   0.20793499]
 [-0.28165166 -0.88202843 -0.55260276 ...,  1.00943696 -0.38352365
   1.34670755]
 [-2.95388857  0.2336112   0.34529161 ...,  1.4521791   0.55438383
  -1.88063162]
 ..., 
 [-1.00601683  1.39260704 -1.50644761 ...,  1.28296402  0.83634446
   0.26208447]
 [-2.47910582 -0.98104329 -1.35478799 ..., -1.73436597 -0.33686111
  -1.02979426]
 [-0.91019123  1.21228964 -1.41039256 ...,  1.48684253  0.62755227
   0.56922418]]
[[-0.43652999  0.19651403 -1.18671182 ..., -0.7067846  -0.34618019
  -0.42333369]
 [ 0.0773801   0.97647553  0.46714833 ..., -1.10374038  0.31484023
   0.5105357 ]
 [ 0.66220479 -0.6966189   1.38479351 ..., -1.28323502 -1.93943153
  -2.22627089]
 ..., 
 [ 0.05277001  0.83922218 -0.17373071 ...,  2.08174431  2.39501573
  -0.92174316]
 [ 0.90858313 -0.06207718  1.14205289 ...,  1.09871008  0.97628114
  -0.4031051 ]
 [-0.6787556  -0.31770416  0.21357829 ...,  2.94599066  2.24697704
  -0.64041093]]


[[-0.24017724  1.48819392 -0.1724061  ...,  2.16089269 -0.64423603
  -0.43083593]
 [ 0.4871752  -0.05217252 -2.16968068 ...,  0.34253742 -2.50486525
   1.97693143]
 [-0.38653431  0.61653589  0.88230878 ..., -0.36266452  0.65175012
  -1.103735  ]
 ..., 
 [ 1.17508664 -0.8250221   0.19422457 ..., -1.32602712  1.10924238
  -2.28879786]
 [-0.2590827   0.83758945  2.69705847 ..., -0.97489394  0.69247937
  -0.56286217]
 [-0.11574353 -0.54751871 -0.31980001 ..., -0.70016272  0.46577874
   0.13700039]]
[[-0.24541614 -0.69836683 -0.56001669 ..., -1.38945671  0.13636768
  -1.33590286]
 [-0.22382    -1.17463366  1.44415089 ...,  1.07862447  1.0159525
  -0.57741722]
 [ 1.12937319  0.51784442  1.12987144 ..., -0.51159175 -0.2360931
   0.92622293]
 ..., 
 [-0.72450189  0.15219701 -1.01592309 ...,  0.20588157  1.79140039
   0.16197135]
 [-0.47316166 -1.29953152  1.03733647 ..., -0.36236085  0.92927732
   1.31247509]
 [ 2.92368883 -2.06244247  1.52312735 ...,  0.23893671 -1.14912893
   1.09439229]]
[[

[[ -1.55531028e+00   4.72916608e-01   1.67386690e+00 ...,  -7.86126901e-01
    2.27687916e+00  -3.50552968e-01]
 [ -9.38063659e-01   7.87564312e-01   8.92246647e-01 ...,   1.96179739e-01
    8.90678788e-01   7.17226988e-01]
 [ -9.14639355e-01  -1.78183743e+00  -1.49567927e+00 ...,   1.06263220e+00
    1.93718784e+00  -6.24504132e-01]
 ..., 
 [ -1.02787573e-03   1.01346673e+00  -4.66130829e-01 ...,   1.58927395e+00
   -1.75741617e+00   3.91516962e-01]
 [ -1.52893381e+00  -3.16500433e+00  -1.30047385e+00 ...,  -2.18122466e+00
   -2.87050376e+00  -7.97746382e-01]
 [ -8.87005971e-01  -1.07850177e+00   2.18807512e-01 ...,  -8.02947540e-01
    1.78178305e-01  -6.79611704e-02]]
[[ 0.2163838   1.43436307 -1.81869448 ...,  1.95056822 -1.12299298
  -0.74196081]
 [-1.34480361 -0.30624498  1.09660163 ..., -1.75232802  0.67464534
   0.2473926 ]
 [ 1.29303999  0.10363749 -1.02967536 ...,  0.43166322 -0.26258863
  -0.03375568]
 ..., 
 [-1.64723138  0.1640318   1.62809978 ..., -2.54934944 -0.07443389


[[ 0.31323821  1.77928883  0.13060259 ...,  1.06235809  0.56652839
   0.63128383]
 [-1.54739512  1.90672545 -1.04854085 ..., -0.10567408 -0.46086343
   0.80515279]
 [ 0.36566517 -1.59839841 -2.08871108 ...,  0.00471587 -1.25985794
  -1.97375118]
 ..., 
 [-0.02880861  1.73833621  1.36195834 ...,  0.42060495 -0.7517829
  -0.25051395]
 [-0.28319723 -0.96712516  2.00723002 ...,  1.03629351 -1.6835057
  -1.54855915]
 [-1.37572723  0.96402749  0.46904828 ...,  0.24450005  0.60915874
   1.37445611]]
[[-0.60556022  3.10350888 -0.23937067 ..., -0.25701362 -0.9725632
   1.02020721]
 [ 1.21511866 -1.79690134 -1.49139435 ...,  0.09449348  1.11042295
   0.80910191]
 [ 1.12826678  0.27984512  0.03160552 ..., -0.45737079 -0.39788721
  -0.34055631]
 ..., 
 [-0.95884313 -0.22382257 -0.54241698 ..., -0.72397012  0.50841146
   0.97569694]
 [-0.25373213 -0.8011535  -0.0706177  ...,  0.74314197 -0.62663346
   0.78070471]
 [-1.58730625 -1.6048651  -0.0624198  ...,  0.04399788 -0.75859556
  -1.06549687]]
[[ 

[[-0.4069139   1.69025335  0.79691672 ..., -0.16568853  0.91436079
   0.35391239]
 [-0.66482841  1.87605922  0.60252275 ...,  1.58255116  0.01685144
  -0.61798611]
 [-0.93800272  0.43424781 -1.4115468  ...,  0.07233732 -0.68774711
   0.60469943]
 ..., 
 [ 0.36858737 -1.99904422 -0.11647783 ..., -1.52543977  0.74712019
  -0.53911884]
 [-0.98902549 -1.40489429  0.19758643 ..., -3.56488682  0.0237539
   0.56650886]
 [-0.70262052  0.14139057  1.21201277 ..., -1.90695033  0.62621437
  -0.71110206]]
[[ 1.18151431  0.46302043 -1.91774381 ..., -0.09446704  1.39213699
  -1.00404839]
 [-1.21162704 -0.39467709  0.46583157 ..., -0.20317867  0.33978     0.10278551]
 [ 1.55726808 -1.36448361 -0.74744461 ...,  0.68791527 -1.74684564
  -0.01796572]
 ..., 
 [ 0.97571668 -0.04860758  0.55223556 ..., -1.70201756 -0.59137816
  -1.48997915]
 [ 2.57040841 -1.56605812 -0.12172258 ...,  1.4712668  -2.00783025
  -0.59757008]
 [ 0.17248481 -0.38179536  0.14141515 ..., -2.00281045 -1.70451214
  -1.34138624]]
[[ 

[[-0.65932695 -0.16132656 -0.93923781 ...,  2.06088811 -0.88256947
   0.8572769 ]
 [ 1.20972577 -2.19411625  0.70980753 ...,  0.25431447  2.1983202
  -1.19178019]
 [ 1.02491729  0.73852286 -1.10912545 ...,  1.40022882 -0.77797284
  -0.355631  ]
 ..., 
 [-0.42017513  0.12688691  0.00272086 ..., -0.16565661 -0.94576347
   1.28512635]
 [ 0.47837108  0.25498841  1.67538943 ..., -0.16447631 -1.0340894
  -0.8193545 ]
 [ 0.68678784  1.70103475 -0.58967947 ...,  0.55221818 -0.04409306
  -0.90683093]]
[[-0.00777412  0.11093832  0.67669207 ..., -0.34838429 -0.2445588
  -1.03468069]
 [ 0.57591547  1.62622578 -1.9988213  ..., -1.71297579 -1.28908722
   1.34645395]
 [ 0.65156872 -1.40630044  0.27589509 ...,  0.63771168  0.80429826
  -0.30421505]
 ..., 
 [-1.81106459  0.64732735 -0.01387605 ...,  0.25159061 -0.7881519
   0.70427998]
 [-0.92151063 -0.07023565  0.08665325 ..., -0.67046848 -1.0237291
  -1.1917697 ]
 [-1.47420824  0.29660172  0.3962816  ..., -0.01874657  0.26473607
  -0.67609491]]
[[ 0.

[[-2.34316806 -0.36160836  0.95853261 ..., -0.48169661 -0.22828399
  -0.45681645]
 [ 0.09898874 -0.47848232 -0.36682037 ..., -2.82532059  0.53080222
   0.40957851]
 [-0.57049955  0.119814   -0.72853403 ..., -0.93410703  0.04374459
   0.52076223]
 ..., 
 [ 0.12104866  0.42888167 -0.0255658  ..., -1.87139087 -0.81425511
  -1.01278818]
 [-0.46203972 -0.76335519  1.22181824 ...,  0.07536445  0.45006399
  -0.05128278]
 [-0.65141184  2.10739056  0.74220916 ...,  1.391308   -1.11358459
  -0.21107422]]
[[ 0.52089595 -0.20507406 -1.74668296 ...,  1.557931   -0.3064546
   0.86824753]
 [ 0.39399342  0.98801513  0.1865393  ...,  0.58531306 -0.95225402
   0.73837392]
 [-0.0706241  -1.53990064 -2.24470578 ..., -1.24335892 -0.99957712
   0.08055003]
 ..., 
 [-1.06272246  0.00944353 -0.06070129 ..., -1.11126887  0.16802995
   1.18674965]
 [-1.88822578 -1.34688864  0.26842512 ..., -0.21745447  0.3571549
   0.90436351]
 [ 0.26065922  0.43714621  1.17318443 ..., -0.51088335 -0.0130495
  -0.52249147]]
[[-

[[ 0.06298402 -0.74643243 -0.69093194 ...,  0.69282737 -1.66913339
  -0.54362587]
 [-0.41184139  0.57903204  0.61067797 ...,  0.67012484 -1.38170028
   0.93261399]
 [-0.16728518  1.42800919  1.44005925 ..., -0.10327154  0.97441274
  -1.08434061]
 ..., 
 [ 0.30041213  1.65827618  0.15413191 ..., -0.01763516  0.21266891
   0.21491055]
 [ 0.10282404  0.89446504 -1.79449866 ...,  1.10368073  0.05945346
  -0.1862547 ]
 [-0.46702128 -0.45336654 -1.14498609 ..., -0.35021508 -0.68014755
   0.51977209]]
[[-0.12733943 -0.77205378 -0.23546237 ..., -0.95693922  0.04222737
  -1.75360473]
 [ 0.63932971 -0.35646027  0.70827843 ...,  0.1650443   0.40193355
  -0.30485584]
 [ 0.17126215  0.95607809 -0.50529493 ...,  1.592267    1.31948034
  -0.52112542]
 ..., 
 [ 0.49752613 -0.52803722 -0.80192047 ..., -3.3590996   0.08215203
   0.47168601]
 [-0.84689706  0.18733818 -1.04675337 ..., -1.63939327  1.36350593
  -0.62450782]
 [ 0.30579611 -0.993786   -0.12900038 ..., -0.86913414 -0.61590148
   1.01237252]]


[[ 0.26219391  1.24243712 -0.46623456 ..., -0.10325548 -0.41743532
   0.51500316]
 [ 1.30634616  0.11313616 -1.2193041  ...,  0.64774202  0.41489607
   0.92929484]
 [ 0.57759078  0.64896836 -0.00977304 ..., -0.80325878 -0.72463237
  -0.78890639]
 ..., 
 [ 0.60060734 -1.24225759  2.12407139 ...,  1.13291475  0.17598626
   0.22797106]
 [-0.74207274 -0.14109356  0.88061874 ..., -0.44367975 -0.25160337
   0.23860491]
 [-0.86515588 -1.09252844  1.14977697 ...,  1.43059493 -0.98812451
   0.85710253]]
[[ 0.52003721  0.07446733  0.22567192 ...,  0.03329499  0.12993028
   1.21803629]
 [ 1.06388346  0.68490465  0.81385031 ...,  0.30576861 -0.62119782
  -0.32308323]
 [-0.86771202  0.27373066 -0.2559575  ..., -0.09545587 -0.63726323
  -0.01530643]
 ..., 
 [-0.73209251  0.61410449 -0.1918946  ..., -0.94630599  1.35500989
  -0.43830286]
 [-1.13848154  1.02449012  1.96865076 ..., -0.70697941 -1.39822497
  -0.4690701 ]
 [ 1.00747823 -0.61089539 -0.58760279 ...,  0.44609179 -1.36322048
  -1.44076249]]


[[ 0.25634411 -0.17154453 -0.2745886  ...,  0.28120588 -0.12547806
   1.56715054]
 [-0.02339652 -2.35585875 -1.33393752 ...,  1.27793761 -2.25164968
   0.82090119]
 [ 0.08715347  0.95005391 -0.15033654 ...,  0.82866132 -1.34107085
   0.28891981]
 ..., 
 [ 0.28519005 -0.4535136  -0.59842643 ...,  1.64151805  0.99771942
  -1.31595018]
 [-1.48615269 -0.65186248 -1.50354387 ...,  1.12556375 -0.17219242
   0.40285917]
 [-1.12657162  1.6284787  -1.67351814 ...,  1.49889077 -0.54355722
   1.42485635]]
[[-0.39651164 -1.72565595 -1.26906663 ...,  0.8958099  -1.27033652
   0.44698197]
 [ 0.37882691  1.05141893  0.26497776 ...,  0.19230135  1.26442135
  -0.66696437]
 [-0.12222293 -0.20705733 -1.37211513 ..., -0.9774047   1.23538305
  -0.99466873]
 ..., 
 [-0.43251146  0.76144684 -1.40151854 ..., -0.54560001 -0.07344467
   1.35985444]
 [ 0.40602076  0.63660074 -2.07483263 ..., -0.75394953  0.69832798
   0.60896286]
 [ 1.03513247  0.1052902  -2.31419162 ..., -2.0959557   0.58630818
   0.45626285]]


[[ 1.22840973  0.59138259 -0.91582282 ...,  0.0905838  -0.15705246
  -1.31857376]
 [ 0.31626094  0.08763171  0.88145247 ..., -0.67944563 -1.13190134
   0.81355409]
 [ 0.74988975 -0.97519917  1.30895799 ...,  1.28308314  0.37796676
  -0.10707274]
 ..., 
 [ 0.55663364  0.4444035   0.95421027 ..., -0.9195252  -0.40073681
  -1.29177659]
 [ 1.13749209 -0.40344113  0.56537467 ..., -0.33468972  0.76063919
   1.35397265]
 [ 0.16313466  1.28295627 -1.04094883 ...,  0.39135363 -1.98991024
  -0.94101341]]
[[ 0.41443979 -0.05813583 -0.53413255 ...,  0.46536656  0.1017452
   0.32743172]
 [ 0.45184997  0.45315889  0.16210504 ..., -0.90820336 -1.20542182
  -0.19837603]
 [-0.44424991 -0.14292908 -0.84560178 ..., -0.97098229 -0.24303948
  -1.34040045]
 ..., 
 [ 0.86863169 -1.12224998 -2.00396938 ...,  0.50037794  0.51243827
   0.26231433]
 [ 0.84911753 -0.70538861  0.96131577 ..., -0.22218158  0.47771026
  -0.18514105]
 [ 0.55436004  0.06937821 -1.40174998 ...,  1.47690507  0.26665702
   0.3751902 ]]
[

[[ 2.32948433 -2.29115075 -1.177004   ...,  1.27683137 -0.19172589
  -1.46309209]
 [ 0.49938066  0.41384522  1.12022129 ...,  0.42917619 -1.68799348
  -0.68110852]
 [-0.46537372 -0.29806617 -0.70219192 ...,  0.55942379  1.71991719
  -1.7661948 ]
 ..., 
 [ 0.91968918  0.44332718  1.70120536 ..., -0.6493136  -2.0829724
  -0.44067646]
 [-0.61937668  0.82725306  1.57543029 ..., -1.55397377 -0.95354657
   0.01840137]
 [-0.66343771  0.10726447 -1.35369658 ..., -0.94530211  0.58139969
  -0.98878547]]
[[-0.43952409 -0.50363784 -0.67303383 ...,  0.20195697  0.93217689
   0.55583078]
 [-0.4369551   0.38928574  1.64327262 ...,  2.21412897 -0.76364451
  -0.79762019]
 [-0.76028182 -0.7857571   0.36647324 ..., -0.79499959 -0.48826989
  -0.16236538]
 ..., 
 [ 1.57601761 -1.20282692  1.23749202 ..., -1.3452804  -1.3335759
  -0.67164073]
 [-0.52389996  0.03512387 -0.3550652  ...,  0.29600144  0.19598771
  -0.63612975]
 [ 0.2753882  -0.18703433 -1.20713017 ..., -0.58206522  0.35796911
   0.05006952]]
[[

[[-1.47148689 -0.44352787  0.06806969 ...,  0.24741224 -0.11805582
   1.54151435]
 [ 0.33795628 -0.54719688  1.07371003 ..., -0.15636224  2.02187895
  -1.57428235]
 [-0.18033147  1.53325313  0.24704509 ...,  1.27997993 -1.37106242
  -0.35514577]
 ..., 
 [ 1.12682895  0.21879817 -0.60548642 ...,  1.2284352   1.79751962
  -0.16389523]
 [ 0.30744055 -0.29206176 -0.81579883 ...,  1.39734096  2.19577061  0.82745   ]
 [-0.17504134  1.69159703  1.47721176 ...,  1.04872853  0.20805041
   0.67877802]]
[[ 0.59810204 -0.74153927  1.45857501 ..., -1.81903034  0.23366467
  -1.07632432]
 [-0.95171788  0.90910601 -1.21560127 ..., -0.16642116 -1.27220903
   1.15572172]
 [ 0.54948809  0.72333644  0.36348431 ...,  0.42292562 -0.47743062
   2.01682588]
 ..., 
 [ 0.88057107  0.11250087  0.63589147 ..., -0.60683934 -0.27625472
   2.45144826]
 [ 0.19476707 -0.15176881  1.13991637 ...,  0.26855321 -0.4176024
   1.28355874]
 [ 0.89217746  0.39202726 -1.15354627 ..., -0.38509222  1.23593207
   1.26643126]]
[[-

[[ 2.65286063 -0.89730089 -1.21041749 ...,  1.35796984  0.53146886
   0.50484731]
 [-1.41213395 -0.16470234  0.0445394  ..., -2.0863114  -1.6158642
   0.31404311]
 [-0.03139373 -0.76065414 -0.40306373 ...,  0.26662837 -0.37634953
  -1.40380367]
 ..., 
 [ 1.1875287  -0.25016355  0.27194027 ..., -1.18344438 -0.98135039
   0.97486865]
 [ 1.76839792  0.5897049   0.44577409 ...,  0.60585509  0.83897864
  -0.59169571]
 [ 1.5275979   0.65747081  0.83203875 ..., -0.13033381  0.07158676
  -1.2487443 ]]
[[-1.11091288  0.10805058 -0.11826683 ...,  0.43182718 -0.30389448
   0.77917763]
 [-0.16919578 -2.05412546 -0.90261235 ..., -0.02546106 -1.09661584
   1.18500713]
 [ 0.51846756  2.21546487 -0.2122869  ..., -2.8970867   0.39449105
  -1.96685634]
 ..., 
 [-0.44772507  1.35830262  1.8218045  ..., -0.76346838 -1.20921265
  -0.40927592]
 [ 0.79247187 -0.1538581  -0.98000027 ..., -0.75396932  1.35774595
  -1.37996353]
 [-0.07443785  1.11043842  1.14888993 ..., -0.733371    0.21545535
  -1.41802023]]
[

[[-0.41510591  1.42392793 -1.0669999  ..., -0.99311358  0.70356828
   1.06722006]
 [ 0.83163185 -0.44488191  0.05058797 ..., -1.64954697  0.6450193
   0.15088019]
 [-1.36479939  0.16743664 -1.55263365 ..., -0.11227521 -1.31984082
   1.18356152]
 ..., 
 [ 0.84778876  0.68091731 -0.42234362 ...,  0.64921163  0.85911367
  -1.7378882 ]
 [-0.2633068  -0.22493118  1.35324601 ..., -0.40888237  0.69613498
  -1.94985789]
 [ 2.22069935  2.37365844 -0.315108   ..., -0.13768297  1.07061987
  -0.51538696]]
[[ -4.87348262e-01  -4.83875766e-01  -6.19124047e-01 ...,  -4.60879491e-01
    7.63184343e-01   6.48710451e-01]
 [ -1.91761139e-01   8.71863440e-01  -1.33257619e+00 ...,   1.51076563e-04
    1.34288354e+00  -4.73099522e-01]
 [ -4.48592014e-01  -7.85576314e-01   4.70530754e-01 ...,   6.76347841e-01
   -4.50551030e-01   8.34832384e-02]
 ..., 
 [ -2.88797633e-01   4.47850726e-01   2.29558902e-01 ...,  -1.04972748e-01
    5.25836641e-01   1.41396449e+00]
 [  4.62855898e-01   3.03277851e+00   1.828003

[[ 0.51534142 -0.55008838  0.9963513  ...,  0.46808977 -0.50639307
  -1.23732907]
 [-0.44334437 -0.72362562 -0.73087241 ...,  0.7636396  -0.35912182
   0.17614842]
 [-1.05456942 -0.08343781  0.03362427 ...,  0.51406136  0.21683299
  -0.64367296]
 ..., 
 [-1.65684193 -0.04185615  0.83846331 ...,  0.02989536 -0.31817582
  -1.14053147]
 [-0.81032952  0.56616441 -0.43825918 ...,  1.92712194  0.60368152
   0.08565265]
 [-0.90034083  0.48047057  0.17861817 ..., -0.79508474 -1.47398366
  -0.92010374]]
[[ -2.22546588e-01   5.11850409e-01  -8.54506631e-01 ...,  -7.11765602e-04
    2.77884772e-01  -4.27874706e-02]
 [ -6.55687179e-01   5.58948566e-01   1.61504810e+00 ...,   4.27293145e-01
    1.06040355e+00   5.52407208e-01]
 [ -2.73566042e-01   5.15960476e-01   8.99868714e-01 ...,   1.74510936e+00
    1.00400513e+00   8.60239059e-01]
 ..., 
 [  6.86808453e-01   1.51709544e+00  -1.52140673e+00 ...,  -3.32750246e-01
   -8.80035139e-01  -1.26568595e+00]
 [  2.29526540e+00   1.30889476e+00   1.01191

[[-1.65730392  0.44281345  1.12427947 ..., -0.62459439 -0.79844602
  -1.07802954]
 [ 0.62596017 -0.61751015  0.38126461 ..., -0.59228253 -0.13442099
   0.91923477]
 [ 0.27007704  1.50548519  1.18889367 ...,  0.41583245  0.00869439
   1.99403338]
 ..., 
 [ 0.95333238  0.28011624  0.20607445 ...,  0.51879366 -0.80991782
   1.43151729]
 [ 1.36564616 -0.30017544  0.67785338 ...,  1.38097605 -1.47924628
   1.01465184]
 [ 2.05926201 -0.08522188  0.80433043 ...,  1.16205297  0.18172724
   0.75173465]]
[[-0.01391958 -0.48783948 -1.84810541 ..., -0.19278665 -0.36401644
   1.11592417]
 [-1.73480316 -1.11321245  0.01089602 ..., -0.10000885  0.50471264
  -0.46021434]
 [ 0.24566611 -0.23002445 -1.16996046 ..., -0.89320799  1.87018982
  -0.65351347]
 ..., 
 [-1.5930355   1.50627666  0.3979932  ..., -1.56470723 -0.02368759
  -0.67296008]
 [-0.44225998  0.37120832 -1.37735511 ...,  0.0386609   0.62775297
   1.76090814]
 [-1.53436451  0.98446909 -1.0512218  ..., -0.59005948  0.60239829
   0.28275738]]


[[ 0.28540825  0.04258514  1.95748226 ..., -0.17578307  0.27711285
  -1.97883593]
 [-0.13082758 -0.02564923  0.19250517 ..., -0.06567325  0.85089573
   0.6504663 ]
 [-0.31704441  0.72586073  1.77496505 ..., -2.19228421  0.19729418
   0.21243031]
 ..., 
 [-0.40137227  1.05091948 -0.55559699 ...,  0.10260637  0.14114056
   0.13742622]
 [ 0.01119197  0.697814    1.91426944 ...,  1.12729699 -0.59657468
  -1.34912467]
 [ 1.38132725 -0.70070209  0.99322418 ...,  1.92822777 -1.57993253
  -0.21195555]]
[[ 0.67785791  1.04999264 -0.79553918 ..., -0.43619902  0.22476005
  -1.27717316]
 [-0.89514158 -0.15524007  0.64373717 ...,  1.84094756 -1.04133442
  -0.39588081]
 [ 0.674749    0.09230022  0.36200908 ..., -0.03022074  1.19756232
   0.87463319]
 ..., 
 [-0.1813116  -0.54823601  0.06722638 ...,  0.0511642   0.30433734
  -0.02198969]
 [ 1.20356467  0.23192297 -1.52909125 ..., -0.18264379  0.31677161
  -0.61038271]
 [-0.60176392 -0.94951025 -1.43405741 ..., -0.51201697  1.15402109
  -0.83367375]]


[[-1.96010279 -0.77928319  3.0604887  ..., -1.53243595  0.54826251
   0.45636747]
 [ 0.57153902 -1.80039611  0.44822718 ..., -1.64755705  0.78107042
   0.27313499]
 [-1.12809928  1.69464266  1.44246534 ..., -0.80783995 -1.05758239
   0.61375628]
 ..., 
 [ 0.55139988  1.14481413  0.48178912 ..., -1.43940415 -0.89340037
   1.37137252]
 [ 0.2814654   0.53244723  0.14827161 ...,  0.22399695  0.93590041
   1.678229  ]
 [ 0.17958843  0.97155864 -0.47747924 ...,  0.65899184  1.52669075
  -0.53768803]]
[[ 0.8736289   0.97353172 -0.03650318 ...,  0.52993891 -0.70268501
  -0.12303191]
 [ 0.73272019 -0.95515741 -0.66182052 ..., -0.18439296  2.03112483
  -0.40404311]
 [-1.93381554  1.23245609 -0.80692548 ..., -0.03748592  0.86811057
  -0.32198134]
 ..., 
 [ 1.55496284  0.10380362 -0.61790436 ...,  1.86967298  1.15334121
   0.21250038]
 [-1.34245491  0.97875094  0.80236526 ..., -0.12685904 -0.42782617
  -0.40111815]
 [ 0.91001217 -0.28296613 -0.53804464 ..., -1.16865303 -1.63792377
   0.03776573]]


[[ 0.2197574  -0.18839053 -1.16437493 ..., -2.05566056  1.47184499
  -1.12620052]
 [ 1.47056783  0.06987816  0.90201475 ...,  0.01808487 -0.2316044
   0.64092221]
 [-1.44171811  0.28642784  0.67407597 ..., -1.85719606  0.00302753
   1.07856321]
 ..., 
 [-0.62234052  1.40868917  0.62193635 ...,  0.5085465   1.01020943
  -0.65611833]
 [-0.8345875   0.39209332  1.20583674 ...,  0.3512743   0.25635551
  -0.97575042]
 [-1.11239119  0.37898166 -0.71210411 ...,  1.2850085   0.34106037
  -1.86615441]]
[[ 1.49145003 -0.58519801  1.19024937 ...,  0.01760369  0.98356744
   2.24210291]
 [ 1.80459567 -0.01504793 -1.40128122 ...,  0.48337504 -0.22871259
   1.8197214 ]
 [-0.42696822  0.58197838  1.91712342 ...,  1.3102776  -0.18410272
  -0.53213922]
 ..., 
 [-0.43443559  1.281642   -1.64145381 ..., -1.32725476 -0.91055202
  -1.42024311]
 [ 1.11366737  0.3335374  -1.08244399 ..., -0.52469213 -0.96940276
  -0.38176834]
 [-0.94653843  0.36981483 -1.01794762 ..., -0.32942467  2.82917683
   0.5335345 ]]
[

[[ 0.68306182 -0.28328952  1.14852605 ...,  0.71540004 -0.69234003
  -0.80284334]
 [ 0.52966892 -1.70732281  0.62145958 ...,  0.93309821 -0.19677428
   0.40933888]
 [ 1.40389215  1.46119083 -0.99340866 ..., -0.05838923  0.45843732
  -0.3835235 ]
 ..., 
 [-0.35578766  1.59714459 -0.75486041 ..., -2.58611746  0.65595661
   0.35478959]
 [-0.95531518 -0.67489146 -1.13304041 ..., -1.25300921  2.83873355
   0.87449737]
 [-2.17589636  0.22083841  0.04268006 ..., -2.43797136  1.30218663
   1.80279592]]
[[ 0.04663284  0.46441245 -0.23523033 ...,  1.58761829  0.6426321
  -0.1550839 ]
 [ 0.34127363 -0.30806186  0.32935305 ..., -1.3703519   1.0725588
  -1.33417243]
 [ 0.20786825  0.28791317  1.17459658 ..., -0.34007745  0.29967036
  -0.38697338]
 ..., 
 [ 0.7891435   1.26260231  0.35035351 ..., -1.72830465  0.36250299
   1.09034992]
 [ 0.50333161 -0.29126285  0.17859203 ..., -1.13284295  1.2876603
   0.88227236]
 [-0.63404925  1.38993175 -1.23126226 ..., -0.75791996 -1.45821153
  -1.28976536]]
[[-

[[-2.03875025  0.07745692 -0.90257423 ..., -0.29188328 -0.38565527
  -1.06517797]
 [-0.01381855 -1.37478579 -0.78875588 ...,  0.47255611  1.06474954
   0.44055834]
 [-0.01500474 -0.08190902 -0.57743078 ..., -0.63171592 -0.82470013
  -0.60211665]
 ..., 
 [ 0.98516149 -1.4249867   1.83101479 ..., -0.36321158  1.33599638
   0.93089327]
 [ 0.23877688  0.23688074 -0.73017736 ...,  1.51241669 -0.43528878
   0.7171269 ]
 [ 0.02012002 -0.44393175  0.6918565  ..., -0.70273221  0.59139339
   0.3663447 ]]
[[-2.36028338  0.71888186 -0.75932057 ..., -0.95275745  1.11657121
   0.03596264]
 [-1.79855967 -0.54422452  0.33341061 ..., -1.31478627 -0.88997508
   0.24328387]
 [-0.09300677 -0.3217897   0.26620294 ...,  0.61851621 -1.38735197
   1.79021438]
 ..., 
 [ 0.24301831 -2.28444963 -0.39656157 ..., -0.95816637 -0.65324916
   0.24550822]
 [ 0.48460726 -0.85770982 -0.59638618 ...,  0.37452187 -0.15732467
   0.40297675]
 [-0.51288488 -0.26112425 -0.54355372 ...,  0.13732548 -0.31381473
  -0.14264036]]


[[-0.65683976 -0.3258187  -0.31993263 ..., -0.15147567 -1.1405023
   1.19319795]
 [ 0.43270658  2.39239905  0.06134278 ...,  1.21346044 -1.08891527
   0.25468639]
 [ 1.02512678 -1.29601994 -0.02626063 ...,  0.53093955  0.30673933
   0.06518038]
 ..., 
 [-0.27721263  0.74310446  0.24648589 ...,  1.02658274  1.58288944
  -1.27767904]
 [ 1.45619251 -0.55329407  0.46736904 ...,  0.87333877 -0.0914843
  -0.62150626]
 [-0.0948297  -0.65822962  1.18646643 ..., -0.19809315  0.07836865
   0.65578015]]
[[-2.32702867  0.21042145  0.53137418 ...,  1.01014346 -1.0305026
  -0.19929953]
 [ 0.03514948  0.25029983  0.61105177 ..., -2.07015793 -1.35171775
   1.59335834]
 [ 0.89351169  0.00940242 -1.62166269 ...,  0.41566868  0.32546457
   1.0060435 ]
 ..., 
 [-0.26046317  1.59308288 -0.59990643 ..., -0.39780566 -1.08728025
  -0.43723029]
 [-1.26634547 -1.42398856  0.88410399 ...,  0.25860235  0.13643998
  -0.52097541]
 [ 1.47119552  0.48340807 -0.46399636 ..., -1.01419789 -0.5776088
   0.24889414]]
[[ 0

[[-0.67753472  0.55805291 -0.79680258 ..., -0.42291306 -0.12468678
   0.72335729]
 [ 0.97143363 -0.14131293 -0.30473202 ...,  0.23748755 -0.96487079
   0.92075264]
 [-0.1174291  -0.18291999  0.67545063 ..., -0.11983231 -0.93035759
  -0.50715712]
 ..., 
 [ 0.56001783 -0.02937457 -0.23016879 ..., -1.27783118 -1.73904642
  -2.23741107]
 [ 1.18800741  0.58468083  0.64305567 ...,  1.38709376 -1.05532377
   0.67345563]
 [-1.00088714  0.38486029 -0.62406029 ...,  0.20880433 -1.89537961
  -0.44286419]]
[[ 0.45634489  1.31005644  0.654738   ...,  1.61342058 -0.5884741
  -1.35173251]
 [-0.208357   -1.12224446 -1.93816731 ...,  0.28661823 -1.7212515
   1.98653296]
 [-0.74508931  1.0997163   1.20147299 ...,  0.69625252  0.35973784
  -1.22702799]
 ..., 
 [-0.86600192 -0.872147   -1.45289412 ...,  0.38051194  1.61398996
  -0.25505312]
 [ 0.66320047 -0.2826882   0.82312544 ..., -0.12490217  1.92263834
  -0.63353871]
 [-0.10001384 -1.81297654  0.19011327 ..., -0.38997359 -0.25350964
  -1.32609573]]
[[